// Generated by Bison
#include "parser.tab.h"
// #include "global.h"
#include <iostream>

using namespace std;



/* BUILT-IN FUNCTIONS */ 
int bye(){
    cout << "bye function exexcuted" << endl;
    return 0;
}

int cd(){
    cout << "cd function exexcuted" << endl;
    return 0;
}

int alias(){
    cout << "alias function exexcuted" << endl;
    return 0;
}

int setenv(){
    cout << "setenv function exexcuted" << endl;
    return 0;
}

int printenv(){
    cout << "printenv function exexcuted" << endl;
    return 0;
}

int unsetenv(){
    cout << "unsetenv function exexcuted" << endl;
    return 0;
}


int main() {
    while(true){
        cout << "[nutshell]>> ";
        int ret = yyparse();

        if (ret == 0) { break; }
        // cout << ret << endl;

	}

    return 0;
}