// Generated by Bison
#include "parser.tab.h"
#include "global.h"
#include <iostream>

using namespace std;

/* GLOBALS */
string PATH;
string HOME;

const char* getPATH(){
    return PATH.c_str();
}

const char* getHOME(){
    return HOME.c_str();
}

/* BUILT-IN FUNCTIONS */ 
int tester(){
    cout << "this is testing tester" << endl;
    return 0;
}

int bye(){
    cout << "bye function exexcuted" << endl;
    return 0;
}

int cd(string* word){
    cout << "cd function exexcuted with word " << word << endl;
    return 0;
}

int alias(){
    cout << "alias function exexcuted" << endl;
    return 0;
}

int setenv(){
    cout << "setenv function exexcuted" << endl;
    return 0;
}

int printenv(){
    cout << "printenv function exexcuted" << endl;
    return 0;
}

int unsetenv(){
    cout << "unsetenv function exexcuted" << endl;
    return 0;
}

int main() {
    HOME = getenv("HOME");
    PATH = getenv("PATH");
    cout << "Path is " << PATH << endl;
    cout << "HOME is " << HOME << endl;
    while(true){
        cout << "[nutshell]>> ";
        int ret = yyparse();

        if (ret == 0) { break; }
        // cout << ret << endl;

	}

    return 0;
}